### ISSUE TITLE
Freshly installed app starts in a strange way

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/cryptox-android#58]
**To reproduce:**

1. Install new build 1.1.0-qa.5.
2. Start the app.

**Result:**

It seems that app stops and starts again.

**Expected:**

App should just start.

[startApp.mp4](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/72fa75d8-a935-4a0a-96b8-32f6b94402ec/07a12dd5-79aa-41dc-89a2-2fe16a4b1113?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS83MmZhNzVkOC1hOTM1LTRhMGEtOTZiOC0zMmY2Yjk0NDAyZWMvMDdhMTJkZDUtNzlhYS00MWRjLTg5YTItMmZlMTZhNGIxMTEzIiwiaWF0IjoxNzE3NDEwNzM1LCJleHAiOjMzMjg3OTcwNzM1fQ.rppqRNuoTKxFX2BmpcqLS1cIMp21twWbYGyXiRoTav4)

**Comment by Radiokot** [comment]
I can't reproduce it. Can you provide more details? Although I don't think this is a significant issue.

**Comment by mh-concordium** [comment]
I added a video. I could try it on another device. There is not much more to add, I just install fresh app (no seed phrase) and start the app.

**Comment by mh-concordium** [comment]
Hm, okay. I can also see it only on Android 11 for now.

**Comment by mh-concordium** [comment]
I marked it as won't do since it doesn't reproduce consistently.
