### ISSUE TITLE
After cancel, app should route to the parent view

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/cryptox-android#61]
**To reproduce:**

1. Select unshield button.
   1. Password dialogue pops up.
2. Select Cancel.

**Expected:**

Route to the parent screen (list of funds to unshield).

**Actual:**

Routes to More screen.

[route_to_parent.mp4](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/602abeaa-d4d2-4b2a-b82f-2c3434810d55/d5c4f3f7-4c70-4a8d-95c0-3d1a3c0b9c94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS82MDJhYmVhYS1kNGQyLTRiMmEtYjgyZi0yYzM0MzQ4MTBkNTUvZDVjNGYzZjctNGM3MC00YThkLTk1YzAtM2QxYTNjMGI5Yzk0IiwiaWF0IjoxNzE3NDg5NTc4LCJleHAiOjMzMjg4MDQ5NTc4fQ.8kQy0K1Mh8GVnXwhjef7QAj5tNA6PDfnCxGhpfJ-bRM)

**Comment by Radiokot** [comment]
Will be fixed as well as the identical issue on the unshielding transaction screen

**Comment by mh-concordium** [comment]
I was not able to reproduce the issue following the description. Tested in 1.1.0-qa.7.
