### ISSUE TITLE
Button to paste the seed phrase is hidden under on screen keyboard

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/cryptox-android#63]
**To reproduce:**

1. Create new wallet.
2. Go to import.

**Result:**

On screen keyboard pops up automatically making it hard to notice button to paste the seed phrase.

**Expected:**

Button should be visible.

[button_hidden.mp4](https://uploads.linear.app/430cc2b6-6b19-45f6-b7f0-6a0093e10c15/53c1fdb2-1169-4369-a6d8-d4b0bf4c38b4/69c92940-baae-4b75-adac-bfbe8127bbd7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzQzMGNjMmI2LTZiMTktNDVmNi1iN2YwLTZhMDA5M2UxMGMxNS81M2MxZmRiMi0xMTY5LTQzNjktYTZkOC1kNGIwYmY0YzM4YjQvNjljOTI5NDAtYmFhZS00Yjc1LWFkYWMtYmZiZTgxMjdiYmQ3IiwiaWF0IjoxNzE3NTAwODMxLCJleHAiOjMzMjg4MDYwODMxfQ._L1BNziRXC4MzuD_Zw53L1crBIqWcp-3vO8iwlirtks)

**Comment by Radiokot** [comment]
Asked designers for a solution.
